name: publish

on:
  push:
    tags:
      - "v[0-9]+*"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  publish-docker:
    needs: publish-npm
    name: Publish to Docker registries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: aktriver
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: aktriver/chatwork-api-client
          tag_with_ref: true
